### ISSUE TITLE
cannot get response with index.php

### ISSUE THREAD

**Issue by stlbud** [raspberrypilearning/lamp-web-server-with-wordpress#11]
I must have missed something or need more information. When I get to the point where I make index.php and refresh my browser, I get a blank page. Do I need to change permissions on something? How can I troubleshoot this? 

Thank you

Bill B

**Comment by bennuttall** [comment]
Is the `index.html` or `index.php` file blank?

**Comment by stlbud** [comment]
No. index.html is the original file that comes with apache. index.php has two lines
<?php echo "hello world";
<?php echo date('Y-m-d H-i-s');

Thanks for your help.

Personally sent by
Bill B
"No bytes, pixels or vectors were harmed in the making of this message."
________________________________

**Comment by bennuttall** [comment]
That's a syntax error.

You've opened your PHP tags twice. Try:

```php
<?php echo "hello world";
echo date('Y-m-d H-i-s');
```

Alternatively:

```php
<?php echo "hello world"; ?>
<?php echo date('Y-m-d H-i-s'); ?>
```

**Comment by stlbud** [comment]
Got it, I'll try again tomorrow.


Thank you for your help.






Bill Budenholzer
 
No pixels, sprites, or vectors were harmed in the making of this message.





From: Ben Nuttall
Sent: ‎Thursday‎, ‎September‎ ‎10‎, ‎2015 ‎4‎:‎00‎ ‎PM
To: raspberrypilearning/lamp-web-server-with-wordpress
Cc: Bill Budenholzer





That's a syntax error.

You've opened your PHP tags twice. Try:

<?php echo "hello world";
echo date('Y-m-d H-i-s');

Alternatively:

<?php echo "hello world"; ?>
<?php echo date('Y-m-d H-i-s'); ?>
