### ISSUE TITLE
Incorrect reference to /var/www in worksheet

### ISSUE THREAD

**Issue by rpdom** [raspberrypilearning/lamp-web-server-with-wordpress#13]
During the step "Download WordPress", reference is made to /var/www/ but at the start of the document it says to use /var/www/html/. It should refer to /var/www/html/ in all steps.

Also, I found it necessary to restart Apache after installing MySQL. I think that should happen automatically (maybe a Debian issue?), I certainly don't remember having to do it before. But perhaps that ought to be added at the end of the Install MySQL section, just in case?

**Comment by bennuttall** [comment]
Fixed - thanks. I previously updated these references from `/var/www` as in Wheezy to `/var/www/html` as in Jessie, but looks like I missed a couple.
