### ISSUE TITLE
Add restart before WORDPRESS CONFIGURATION

### ISSUE THREAD

**Issue by mobluse** [raspberrypilearning/lamp-web-server-with-wordpress#14]
You need to restart apache2 before accessing http://YOUR-IP-ADDRESS in the section WORDPRESS CONFIGURATION otherwise the web-server complains about MySQL-modules not installed.

sudo systemctl restart apache2

or

sudo service apache2 restart

(I'm not sure which is best for restarting apache2.)

**Comment by bardicwarrior** [comment]
Pull request submitted #16
