### ISSUE TITLE
Problem downloading "sudo apt-get install mysql-server php5-mysql -y"

### ISSUE THREAD

**Issue by Bow3ryList** [raspberrypilearning/lamp-web-server-with-wordpress#21]
Hi, I am have a problem download the:

# sudo apt-get install mysql-server php5-mysql -y

It comes up with a message saying:

The following packages have unmet dependencies:
 php5-mysql : Depends : libmysqlclient18 but it is not installable
E: Unable to correct problems, you have held broken packages.

I have tried typing in just the following to install mysql

# sudo apt-get install mysql-server php5

And it install something, but it never asks me for a password.

I think I have managed to set up the database, but I get the message:

Your PHP installation appears to be missing the MySQL extension which is required by WordPress.

Is that file source now missing?

Thanks

**Comment by bennuttall** [comment]
Are you on Raspbian Stretch? This might need updating to mariadb

**Comment by junyuzhu** [comment]
Hi everyone.
This day . I get the same problem  .
My "Pi"  is running RASPBIAN ， when i use  **‘sudo apt-get install mysql-server php5-mysql -y**’
I got the same report like  @Bow3ryList  say that. "**The following packages have unmet dependencies:
php5-mysql : Depends : libmysqlclient18 but it is not installable"** 
After that I change the source the install problem was solve.
But，the another problem .I dont konw how to do this .
When I install the mysql-server .  it never asks me for a password with the mysql.
Just go on install and finish it.
Thank you .

**Comment by bennuttall** [comment]
Are you using Raspbian Stretch?

**Comment by Bow3ryList** [comment]
Hi there, I am using Raspbian Stretch. 

Thanks

**Comment by XECDesign** [comment]
This should be `default-mysql-server php7.0-mysql`.

Also, you can't run `mysql -uroot -p` as a normal user. You have to run it as root and add a new user for wordpress.
`grant all privileges on wordpress.* to wpuser@localhost identified by 'somepassword';`

**Comment by Bow3ryList** [comment]
Will it work if you install php 7.0 mysql?

**Comment by XECDesign** [comment]
I ran through the instructions with the changes mentioned above and wordpress runs happily.

**Comment by martinohanlon** [comment]
I have brought this project up to date, all the fixes are in draft. Its just awaiting copy edit as I had to change a lot of stuff!

**Comment by martinohanlon** [comment]
resolved.
