### ISSUE TITLE
Guide needs updating for Raspbian Stretch

### ISSUE THREAD

**Issue by rpdom** [raspberrypilearning/lamp-web-server-with-wordpress#23]
A number of things have because of the release of Raspbian Stretch, most notable is the change from MySQL server to MariaDB. Parts of the guide will need to be updated.

**Comment by rpdom** [comment]
I see that there is a pull request already in place for this issue. I should have looked harder. I do have an updated version of the guide ready to upload, so will compare with the other proposed changes.

**Comment by martinohanlon** [comment]
I have brought this project up to date, all the fixes are in draft. Its just awaiting copy edit as I had to change a lot of stuff!

**Comment by JaninaPi** [comment]
In step 3, line 72 mentions nano, but the code in line 75 refers to leafpad. Please correct.

**Comment by martinohanlon** [comment]
Corrected...

**Comment by JaninaPi** [comment]
Wasn't sure which one was needed, so thanks!

**Comment by martinohanlon** [comment]
Neither was I! I went with leafpad.

**Comment by JaninaPi** [comment]
I've written a paragraph in step 6 to explain a little bit about `.tar.gz`. This is a key bit of knowledge for people who are starting to use open-source software, so I think it makes sense to include it.
Could you 1) check my facts, and 2) move the paragraph into a collapsible section called 'What's `.tar.gz`?' or similar if you think that'd be better.

**Comment by JaninaPi** [comment]
In step 7, add a half-sentence to line 63 to explain what 'Flush the database privileges' means.

**Comment by martinohanlon** [comment]
Done and done. Thank you.

**Comment by martinohanlon** [comment]
Resolved.
