### ISSUE TITLE
MySQL Missing Package (Jun 2019)

### ISSUE THREAD

**Issue by throrik** [raspberrypilearning/lamp-web-server-with-wordpress#31]
On the latest Raspian image following this project users will come across an error when trying to install mysql-server as it's now a deprecated package and has been replaced with MariaDB

```
pi@optimuspi:~ $ sudo apt-get install mysql-server
sudo: unable to resolve host optimuspi: Name or service not known
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package mysql-server is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  mariadb-server-10.0

E: Package 'mysql-server' has no installation candidate
```

I suggest replacing this with the recommended MariaDB-Server package.

**Comment by MarcScott** [comment]
Is this related, from projects feedback

URL: /en/projects/lamp-web-server-with-wordpress/5 Running the line 'sudo apt-get install mysql-server php-mysql -y' fails to install anything and instead errors out with 'package 'mysql-server' has no installation candidate'. Please could these instructions be updated to reflect this, as I'm eager to host a website on my pi. :)

**Comment by martinohanlon** [comment]
Has the package name changed with buster?

**Comment by throrik** [comment]
> Has the package name changed with buster?

MySQL support from the actual repository was deprecated and replaced with MariaDB - so I suspect you'll need to either update the guide to show how to install MySQL manually or update it to use MariaDB packages.

**Comment by m-alzam** [comment]
Hello
I sent a pull request to fix the error. See #32 

Thanks
