### ISSUE TITLE
Issues on multiple steps in project (Sept 2020)

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/lamp-web-server-with-wordpress#44]
Hey Marc, 

These issues were raised this month on the LAMP server project. They're likely to all be from 1 or 2 people given the dates and order of steps. Could you take a look and see if the project needs updating in any way please. 

lamp-web-server-with-wordpress/3 - hello world php doesn't work. mousepad error "them parsing error: <data>:x:xx: the style property GtkButton:inner-border is deprecated and shouldn't be used anymore. index.php will not display "hello world" no matter what is done; even after restart of apache

lamp-web-server-with-wordpress/4 - I did all this and it works. But Mariadb says: error on grant all privileges on etc. etc. so now I am stocked with a not working server. Can't setup WordPress!. 

lamp-web-server-with-wordpress/6 - Hello, I am following along with the steps but i am stuck in granting all privileges. The output i get shows --> Query OK, 0 rows affected (0.001 sec) The command i entered is as follows:  MariaDB [(none)]> GRANT ALL PRIVILEGES ON wordpress.* TO 'root'@'localhost' IDENTIFIED BY '******'; can you please help? my email is gerardo@gismc.us

lamp-web-server-with-wordpress/7 - I am new to raspberry pi. I am building a project named, Build a LAMP Web Server with WordPress with my raspberry pi. I follow all your steps. Now I am wordpress from my local iP but I try to enter database. I get an error establishing a datebase connection. Need help

lamp-web-server-with-wordpress/7 - sudo service apache2 restart. Job for apache2.service failed because the control process exited with error code.

lamp-web-server-with-wordpress/complete - After typing http: // in Chromium and then my localhost number, the message "Your PHP installation appears to be missisng the MySQL extension which is required by WordPress". What went wrong? More importantly, what should I do?

**Comment by MarcScott** [comment]
I've run through this entire project, and followed the instructions. I see none of these issues. It might be that the users are not on the latest OS. I'll add in step 1 to use the latest OS version.
