### ISSUE TITLE
Confusing screenshot with not mentioned code entered. (Nov 2020)

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/lamp-web-server-with-wordpress#47]
Hi!

The terminal screenshot on https://projects.raspberrypi.org/en/projects/lamp-web-server-with-wordpress/6 (i.e. https://projects-static.raspberrypi.org/projects/lamp-web-server-with-wordpress/bc295b5c37b6ebb601dd98bb8d125739d995c4d4/en/images/create-database.png ) is pretty confusing since it suggests that you should log out before proceeding to the "GRANT ALL PRIVILEGES ..." step.

Otherwise, thanks for a very useful set of instructions!

https://projects.raspberrypi.org/en/projects/lamp-web-server-with-wordpress/6

**Comment by libxx1** [comment]
@MarcScott Hiya, can you take a quick look at this please. Are you happy if I crop the screenshot on this page to remove the last couple of lines? 

https://projects.raspberrypi.org/en/projects/lamp-web-server-with-wordpress/6

**Comment by MarcScott** [comment]
Yep @libxx1 you can crop away.
